[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SubspaceClustering = "bea3bcab-479e-4b6c-b047-c6cd33cd022c"

[sources]
SubspaceClustering = {path = ".."}

[compat]
Documenter = "1.10"
julia = "1.11"
